Country selection
MattiaSilvestri/energy-monitor pull request #10
Opened 2023-02-28 18:49 UTC by MattiaSilvestri

Changes:
- user can choose between automatic geolocation and manual country selection;
- minimal cli;
- help message;
- flag for getting country list in alphabetical order.

2023-02-28 19:04 UTC, FrnRmn reviewed
Looks good in general, thanks

2023-02-28 19:04 UTC, FrnRmn commented on README.md
> +
next time I would do this changes outside the branch, just for future commits

2023-02-28 19:04 UTC, FrnRmn commented on src/main.py
> +if args.list:
I would extract the next rows as a function outside main.py

2023-02-28 19:04 UTC, FrnRmn commented on src/main.py
> +if args.list:
possible?

2023-02-28 19:07 UTC, FrnRmn requested changes
I think this is the only necessary change, thanks

2023-02-28 19:07 UTC, FrnRmn commented on src/energymonitor/exceptions.py
> +"""Define custom exceptions"""
to be removed

2023-03-01 21:41 UTC, MattiaSilvestri commented on README.md
> +
Not sure I got it, you mean to not update the README directly in dev or main?

2023-03-01 22:13 UTC, MattiaSilvestri commented
Made some changes:
- removed the exceptions module;
- created the "core" module which will host the scripts handling the core functionalities of the apps. I moved the main there and created a new "cpuCO2" script which will be used only for launching.

2023-03-05 17:38 UTC, FrnRmn commented on README.md
> +
No no, just that the README to-do list seems outside the scope of this"country_selection" branch

2023-03-05 17:47 UTC, FrnRmn commented
so many changes, basically a new pr haha :D
I might need a call to clarify a few things

2023-03-05 20:58 UTC, MattiaSilvestri commented
Yeah sorry ahah, I tried to add the things you asked, but I'm still not very sure about the core package, I just didn't know how to better separe the two parts of the main (user arguments handling and main() funciton), but yeah we can discuss it

2023-03-07 18:15 UTC, merged