Cpu data
MattiaSilvestri/energy-monitor pull request #18
Opened 2023-04-27 20:42 UTC by giulianogiari

2023-05-01 16:53 UTC, FrnRmn requested changes
Thanks for the update. In addition to the specific code line comment, I would try to match the personal CPU model with the database model using the alphanumeric code, as we discussed before!

2023-05-01 16:53 UTC, FrnRmn commented on src/utils/cpu.py
> +                    break
I would change that find algorithm [line 72-79] with something that assures you that the order in which you iterate does not influence the outcome

2023-05-02 17:36 UTC, MattiaSilvestri reviewed
Good, only minor thing is that there are no annotations for the types in input to the functions, something like: `get_cpu_tdp(cpu_name: str) -> float:`
But I'm just being picky, it's not essential.

2023-05-02 17:36 UTC, MattiaSilvestri commented on src/utils/cpu.py
> +                    break
> 

You mean that models deep down in the list will require more time to be located?

2023-05-09 19:29 UTC, FrnRmn commented on src/utils/cpu.py
> +import warnings
It seems warnings is not used in the code

2023-05-09 19:33 UTC, FrnRmn commented
Thanks for the updates, now it looks fine to me

2023-05-11 20:11 UTC, MattiaSilvestri approved these changes
Good to merge for me.

2023-05-11 20:22 UTC, merged